package com.bridegelabz.iplanalysis;

import java.util.Comparator;

public enum SortType {
	BATTING_AVG ,
	STRIKE_RATE,
	MAXIMUM_FOUR_AND_SIXES,
	STRIKINGRATE_WITHFOURANDSIXES ,
	AVERAGE_WITH_STRIKE_RATE ,
	MAXIMUM_RUNS_WITH_BEST_AVERAGE,  BEST_STRIKING_WITH_SIX_AND_FOUR ;
	}
